apiVersion: v1
kind: Service
metadata:
  name: ranjith-micro
  namespace: ranjith
spec:
  selector:
    app: ranjith-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

